Bond angles dihedrals
ur-whitelab/MDCrow pull request #139
Opened 2024-06-10 15:28 UTC by brittyscience

Bond angles and dihedrals code and unit test.

2024-06-14 02:04 UTC, Jgmedina95 commented
Hi Brittany, thanks for working on this. 
My general comments are that this tools as they are, are hard to use, they return a big array of angles and a big array of indices... which I don't believe can be very useful, neither for the agent nor the user. It would be better to at least save the values into a file, but even then, a list of values is not very useful alone. Is not that important to wrap all the mdtraj functions as tools, but rather make general use cases from them.

Here I found some nice plots that could be done with the information from these angles(yes, Ram plots are here too!):
https://dunbrack.fccc.edu/bbdep2010/ConformationalAnalysis.php

Please try to include one or some of these plots, first. The output of the compute_chiX methods are an array of indices and an array of values per angle. 
The documentation states:
```
Returns
indicesnp.ndarray, shape=(n_chi, 4)
The indices of the atoms involved in each of the chi dihedral angles

anglesnp.ndarray, shape=(n_frames, n_chi)
The value of the dihedral angle for each of the angles in each of the frames.
```
So I imagine it may be useful to identify/map which residues correspond to the atom indices for the corresponding plots.
Something like this may be helpful
```
# Create a dictionary to map atom indices to residue names
traj = mdtraj.load(trajectory_path, top=topology_path)
atom_to_residue = {atom.index: atom.residue for atom in traj.topology.atoms}

# For each set of chi1 indices, map them to their residues
residues_per_chi1 = [[atom_to_residue[idx] for idx in chi_set] for chi_set in chi1_indices]

```

2024-06-14 02:06 UTC, Jgmedina95 commented on mdagent/tools/base_tools/analysis_tools/bond_angles_dihedrals_tool.py
> +            plt.figure(figsize=(10, 8))
missing to save the figure with the path registry

2024-06-16 18:34 UTC, brittyscience commented
Thank you for your feedback, Jorge. There still need to be more troubleshooting with the ram plot and the output of indices. Something is still missing, but the code is there. Hopefully it just needs a bit of tweaking.

2024-06-21 13:36 UTC, brittyscience commented
When you have time, I would really appreciate a second set of eyes to see what I am missing here. The script seems to be all set, minus the ram plot. I am missing something here. @Jgmedina95

2024-06-25 21:11 UTC, brittyscience commented
I need a second set of eyes here. More details in Notion stand up notes about this.

2024-06-26 17:00 UTC, SamCox822 requested changes
see the comments I made on the other PRs, most apply to this one too. additionally, can you combine the Chi tools into 1 tool and have the agent specify the type or some other mapping? rather than chi1, chi2, etc. which will probably be difficult for the agent

will the agent ever have a preference of the types?

2025-02-17 17:37 UTC, SamCox822 requested changes

2025-02-17 17:37 UTC, SamCox822 commented on tests/test_preprocess/test_uniprot.py
> +@pytest.mark.skip(reason="Server error")
I dont think we need to skip this -> can you either let it fail or handle the error within the test?

2025-02-17 17:53 UTC, merged